cache: bundler
language:
  - ruby
before_install: gem install bundler
install:
  - 'bundle install'
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: 'bundle exec rake test'
env:
  - COVERALLS=true
